import Config

database_connection_options =
  case System.get_env("DATABASE_SOCKET_DIR") do
    nil ->
      [
        hostname: System.get_env("DATABASE_HOST", "localhost"),
        port: String.to_integer(System.get_env("DATABASE_PORT", "5432"))
      ]

    socket_dir ->
      [socket_dir: socket_dir]
  end

# Configure your database
config :jazida_phoenix,
       JazidaPhoenix.Repo,
       [
         username: System.get_env("DATABASE_USER", "postgres"),
         password: System.get_env("DATABASE_PASSWORD", "postgres"),
         database: System.get_env("DATABASE_NAME", "jazida_phoenix_dev"),
         stacktrace: true,
         show_sensitive_data_on_connection_error: true,
         pool_size: 10
       ] ++ database_connection_options

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :jazida_phoenix, JazidaPhoenixWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "rfwYYgj4nGYK1Pb/XmQL2aIaOk6FQO6QLkvasKg9B3nPH2wT+a0z9P1eyprbPkIn",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:jazida_phoenix, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:jazida_phoenix, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :jazida_phoenix, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
